services:
  - type: web
    name: youtube-summarizer
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        value: 'postgresql://postgres:postgres@localhost:5432/postgres'
      - key: GROQ_API_KEY
        value: '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'
      - key: SECRET_KEY
        generateValue: true
